# Use Ubuntu as base image
FROM ubuntu

# Install Python and pip
RUN apt-get update && \
    apt-get install -y python3 python3-pip curl

# Install Poetry
RUN apt install -y python3-poetry

# Install Git
RUN apt-get install -y git

# Copy and install dependencies using Poetry
WORKDIR /project
COPY pyproject.toml poetry.lock /project/
RUN poetry install  --with dev --no-root --no-interaction --no-ansi

# Copy the rest of your application code
COPY . /project

# Clean up
RUN apt-get clean && \
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

# The command that executes at container start
CMD ["bash"]
